version: "3.9"

services:
  goldmund-sh-api:
    container_name: goldmund-sh-api
    restart: always
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - goldmund-sh-network

networks:
  goldmund-sh-network:
    driver: bridge
